name: speech_xf
description: 该插件集成了讯飞语音识别和语音合成功能。支持Android和IOS平台
version: 1.0.0
homepage: https://github.com/shijia2118/speech_xf.git
repository: https://github.com/shijia2118/speech_xf.git


environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"
  

false_secrets:
  - libmsc.so
  - iflyMSC

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.speech_xf
        pluginClass: SpeechXfPlugin
      ios:
        pluginClass: SpeechXfPlugin

 
